import { Header } from "../components/Header";
import { Footer } from "../components/Footer";
import { Poppins, Marck_Script } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
  variable: "--font-poppins",
});

const marckScript = Marck_Script({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} `}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
