import "./globals.css";

import { Header } from "../components/Header";
import { Footer } from "../components/Footer";
import { Poppins, Marck_Script, Open_Sans } from "next/font/google";


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
  variable: "--font-poppins",
});

const marckScript = Marck_Script({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--font-markScript",
});

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: "700",
  display: "swap",
  variable: "--font-openSans",
})

export const metadata = {
  title: "De SHTORO",
  description: "Generated by Svitlana Kovalenko",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} `}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
